#!/usr/bin/env python3
"""Fast repository checks that do not require LuaJIT or Android tooling."""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

ROOT = Path(__file__).resolve().parents[1]
CHINESE_RE = re.compile(r"[\u4e00-\u9fff]")
ALLOWED_CHINESE_FILES = {
    Path("csv_data/client_lang_zh-CN.csv"),
    Path("csv_data/client_lang_zh-TW.csv"),
}
SKIP_SUFFIXES = {".apk", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".wav", ".mp3"}


def check_no_chinese_artifacts() -> list[str]:
    errors: list[str] = []
    for path in ROOT.rglob("*"):
        rel = path.relative_to(ROOT)
        if ".git" in rel.parts or not path.is_file():
            continue
        # gitignored headless-test fixtures (regenerated by setup_test_env.py)
        # and dependency / build trees that we do not author
        skip_parts = {
            "decrypted", "csv_plain", "sim_save", "sim_save_int", "sim_save_web",
            "node_modules", "dist",
            # web/public/ is the staging dir prepare_web.py fills from
            # decrypted/ + csv_plain/ (gitignored, like decrypted/ itself)
            "public",
            # archive/ holds byte-identical copies of stock game Lua, Chinese
            # comments included, so restoring them is an exact copy
            "archive",
        }
        if any(p in skip_parts for p in rel.parts):
            continue
        if rel in ALLOWED_CHINESE_FILES or path.suffix.lower() in SKIP_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if CHINESE_RE.search(text):
            errors.append(f"unexpected Chinese characters in {rel}")
    return errors


def check_text_loader_forces_english() -> list[str]:
    text = (ROOT / "src/manager/text_loader.lua").read_text(encoding="utf-8")
    if 'local ENGLISH_LANG = "en-US"' not in text or "lang = ENGLISH_LANG" not in text:
        return ["text_loader.lua must force the English CSV in this offline build"]
    return []


def check_campaign_generators() -> list[str]:
    """PR F: the checked-in native campaign module must match the generator."""
    errors: list[str] = []
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts/refresh_campaign_data.py"), "--verify"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        errors.append("refresh_campaign_data.py --verify failed")
        errors.append(result.stdout)
        errors.append(result.stderr)
    return errors


def check_landing_serves_web_game() -> list[str]:
    """GitHub Pages serves repo-root index.html — it must point at the web game."""
    errors: list[str] = []
    text = (ROOT / "index.html").read_text(encoding="utf-8")
    if "there is no web/browser version" in text or "Android-only" in text:
        errors.append("root index.html still claims there is no browser version")
    if "Play in browser" not in text:
        errors.append("root index.html must offer Play in browser")
    if "English_offline.apk" not in text:
        errors.append("root index.html must still offer the APK download")
    return errors


def check_web_recruit_ui() -> list[str]:
    """The browser chooser must actually draft — never auto-skip a first clear."""
    errors: list[str] = []
    ui = (ROOT / "web/src/ui.js").read_text(encoding="utf-8")
    bridge = (ROOT / "web/lua/web_bridge.lua").read_text(encoding="utf-8")
    if "draft UI is a next step" in ui:
        errors.append("ui.js still auto-skips the recruit draft")
    if "renderRecruit" not in ui:
        errors.append("ui.js must render a recruit chooser (renderRecruit)")
    if "recruitOffers" not in ui or "skipRecruit" not in ui:
        errors.append("ui.js must call engine.recruitOffers / skipRecruit")
    if "Skip (+15 EXP)" not in ui:
        errors.append("ui.js must offer Skip (+15 EXP) on the recruit draft")
    if "campaign_service.card(nil" in bridge:
        errors.append("web_bridge still looks up cards with a nil index")
    if "data_template.card_config" not in bridge:
        errors.append("web_bridge.recruit_offers must resolve names from card_config")
    if "req_campaign_skip_recruit" not in bridge:
        errors.append("web_bridge.skip_recruit must go through the server handler")
    return errors


def check_archived_sources() -> list[str]:
    """Archived game modules must stay archived: recoverable, but unshipped
    and unreferenced (see scripts/archived_sources.py)."""
    sys.path.insert(0, str(ROOT / "scripts"))
    from archived_sources import ARCHIVED_SOURCES  # noqa: E402

    errors: list[str] = []
    archive_dir = ROOT / "archive"
    lua_roots = [ROOT / "src", ROOT / "web" / "dist" / "game"]

    for rel in sorted(ARCHIVED_SOURCES):
        # 1. never shipped from src/
        if (ROOT / "src" / rel).exists():
            errors.append(f"archived module must not live in src/: {rel}")
        # 2. never shipped in the browser build
        if (ROOT / "web" / "dist" / "game" / rel).exists():
            errors.append(f"archived module still ships in web/dist/game/: {rel}")
        # 3. recoverable from archive/
        if not list(archive_dir.rglob(Path(rel).name)):
            errors.append(f"archived module has no copy under archive/: {rel}")
        # 4. nothing live may require it
        dotted = rel[:-4].replace("/", ".") if rel.endswith(".lua") else rel
        needle = f'"{dotted}"'
        for root in lua_roots:
            if not root.is_dir():
                continue
            for path in root.rglob("*.lua"):
                if needle in path.read_text(encoding="utf-8", errors="ignore"):
                    errors.append(
                        f"{path.relative_to(ROOT)} requires archived module {dotted}"
                    )

    # 5. the shipped APK must not carry them either (namelist only — no decrypt)
    apk = ROOT / "English_offline.apk"
    if apk.is_file():
        import io
        import zipfile

        with zipfile.ZipFile(apk) as outer:
            if "assets/src.mu" in outer.namelist():
                with zipfile.ZipFile(io.BytesIO(outer.read("assets/src.mu"))) as inner:
                    packed = set(inner.namelist())
                for rel in sorted(ARCHIVED_SOURCES):
                    if f"src/{rel}" in packed:
                        errors.append(f"English_offline.apk still ships {rel}")

    # 6. the browser manifest must not list them either
    manifest = ROOT / "web" / "dist" / "game-manifest.json"
    if manifest.is_file():
        listed = set(json.loads(manifest.read_text(encoding="utf-8")).get("lua", []))
        for rel in sorted(ARCHIVED_SOURCES):
            if rel in listed:
                errors.append(f"web/dist/game-manifest.json still lists {rel}")
    return errors


def check_balance_audit() -> list[str]:
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts/analyze_balance.py"), "--fail-on-critical"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        return ["balance audit found collectible critical outliers", result.stdout, result.stderr]
    return []


def main() -> int:
    errors: list[str] = []
    result = subprocess.run(
        [sys.executable, str(ROOT / "tests/campaign_data_test.py")],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    extra = []
    if result.returncode != 0:
        extra.append("campaign_data_test.py failed")
        extra.append(result.stdout)
        extra.append(result.stderr)

    for check in (
        check_no_chinese_artifacts,
        check_text_loader_forces_english,
        check_campaign_generators,
        check_balance_audit,
        check_web_recruit_ui,
        check_landing_serves_web_game,
        check_archived_sources,
    ):
        errors.extend(check())
    errors.extend(extra)
    if errors:
        print("STATIC CHECKS FAILED")
        for err in errors:
            print(" -", err)
        return 1
    print("STATIC CHECKS PASSED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
