#!/usr/bin/env python3
"""Heuristic balance audit for Monster Battle CCG card data.

The goal is not to replace playtesting. It catches obvious CCG/mobile pitfalls:
- non-collectible/tutorial cards leaking into random pools,
- very cheap cards with boss-level stat packages,
- rarity tiers that buy raw stats instead of interesting choices,
- strictly dominated lower-rarity cards at the same cost.
"""
from __future__ import annotations

import argparse
import csv
import math
import statistics
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CARD_CSV = ROOT / "csv_data" / "all_card_config.csv"

RARITY_LABEL = {
    "normal": "Common",
    "rare": "Rare",
    "rarity": "Epic",
    "epic": "Legendary",
}
RARITY_ORDER = {"normal": 1, "rare": 2, "rarity": 3, "epic": 4}
PRIMARY_ATTACKS = {"melee", "ranged", "magic", "chance"}
UTILITY_WEIGHTS = {
    "aggro": 1.0,
    "antimagic": 1.2,
    "boost": 1.0,
    "cautious": 0.8,
    "cleave": 1.4,
    "counter": 1.0,
    "crystal": 1.6,
    "demoralize": 1.5,
    "disease": 1.1,
    "draft": 1.2,
    "drain_crystal": 1.4,
    "entangle": 1.3,
    "flying": 1.0,
    "heal": 1.1,
    "immunity": 1.8,
    "magic_aoe": 1.6,
    "opportunity": 0.9,
    "rally": 1.4,
    "reflect": 1.4,
    "regenerate": 1.3,
    "shield": 1.3,
    "silence": 1.2,
    "stealth": 1.0,
    "swap": 1.0,
    "thorns": 1.1,
    "thrash": 1.2,
}


def to_int(value: str | None, default: int = 0) -> int:
    if value in (None, ""):
        return default
    try:
        return int(float(value))
    except ValueError:
        return default


def read_cards() -> list[dict]:
    cards: list[dict] = []
    with CARD_CSV.open(encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            if not row.get("ID", "").isdigit():
                continue
            for key in ("ID", "group_id", "level", "hp", "flags", "cost", "score", "deck_limit", "p1v", "p2v", "p3v"):
                row[key] = to_int(row.get(key))
            row["powers"] = powers(row)
            row["attack"] = attack_value(row)
            row["complexity"] = len(row["powers"])
            row["budget"] = budget_score(row)
            cards.append(row)
    return cards


def powers(card: dict) -> list[tuple[str, int]]:
    result: list[tuple[str, int]] = []
    for idx in (1, 2, 3):
        name = (card.get(f"p{idx}n") or "").strip().lower()
        if name:
            result.append((name, to_int(card.get(f"p{idx}v"))))
    return result


def attack_value(card: dict) -> int:
    values = [value for name, value in card["powers"] if name in PRIMARY_ATTACKS]
    return max(values) if values else 0


def utility_score(card: dict) -> float:
    total = 0.0
    for name, value in card["powers"]:
        if name in PRIMARY_ATTACKS:
            continue
        weight = UTILITY_WEIGHTS.get(name, 1.0)
        total += weight * max(1, value)
    return total


def budget_score(card: dict) -> float:
    # HP is highly valuable in this game because it gates survival and board presence.
    # Attack has a larger moment-to-moment impact. Utility is intentionally a rough
    # tax so complex cards can be special without becoming raw-rate monsters.
    hp = to_int(card.get("hp"))
    attack = attack_value(card)
    return hp + (attack * 1.6) + utility_score(card)


def percentile(values: list[float], p: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    idx = min(len(ordered) - 1, max(0, math.ceil((p / 100.0) * len(ordered)) - 1))
    return ordered[idx]


def summarize(cards: list[dict]) -> str:
    lines: list[str] = []
    monsters = [c for c in cards if c["type"] == "monster"]
    collectible = [c for c in cards if c["flags"] == 1]
    special = [c for c in cards if c["flags"] == 0]

    lines.append("# Monster Battle CCG Balance Audit")
    lines.append("")
    lines.append("Generated by `python3 scripts/analyze_balance.py --markdown`.")
    lines.append("")
    lines.append("## Principles used")
    lines.append("")
    lines.append('Research note: the healthiest CCG pattern I found is to separate rarity from raw power: make broadly useful staples common, and make rare cards more specialized/complex rather than simply stronger. See Game Studies, "Rarity and Power: Balance in Collectible Object Games" (https://gamestudies.org/1001/articles/ham). Mobile/F2P monetization guidance says the same thing in practical terms: avoid paid combat advantages, keep fairness, and offer non-paying progression paths.')
    lines.append("")
    lines.append("- Rarity should buy specialization, deck-building texture, and timing decisions, not a direct stat upgrade.")
    lines.append("- Common and Rare cards should remain efficient, readable staples.")
    lines.append("- Legendary cards can be splashy or multi-modal, but their rate must stay inside the same cost budget.")
    lines.append("- Tutorial/boss cards must be flagged out of random rewards and prototype card pools.")
    lines.append("")
    lines.append("## Dataset")
    lines.append("")
    lines.append(f"- Cards: **{len(cards)}** total, **{len(collectible)}** collectible (`flags=1`), **{len(special)}** tutorial/boss (`flags=0`).")
    lines.append("- By type: " + ", ".join(f"{k}: {v}" for k, v in sorted(Counter(c["type"] for c in cards).items())))
    lines.append("- By rarity: " + ", ".join(f"{RARITY_LABEL.get(k, k)}: {v}" for k, v in sorted(Counter(c["quality"] for c in cards).items(), key=lambda kv: RARITY_ORDER.get(kv[0], 99))))
    lines.append("")

    lines.append("## Rarity identity check: level-1 monsters")
    lines.append("")
    lines.append("| Cost | Rarity | Count | Avg HP | Avg Attack | Avg Abilities | Avg Budget |")
    lines.append("|---:|---|---:|---:|---:|---:|---:|")
    level1 = [c for c in monsters if c["level"] == 1 and c["flags"] == 1]
    for cost in sorted({c["cost"] for c in level1}):
        for quality in sorted({c["quality"] for c in level1 if c["cost"] == cost}, key=lambda q: RARITY_ORDER.get(q, 99)):
            bucket = [c for c in level1 if c["cost"] == cost and c["quality"] == quality]
            lines.append("| {cost} | {rarity} | {count} | {hp:.2f} | {atk:.2f} | {abl:.2f} | {budget:.2f} |".format(
                cost=cost,
                rarity=RARITY_LABEL.get(quality, quality),
                count=len(bucket),
                hp=statistics.mean(c["hp"] for c in bucket),
                atk=statistics.mean(c["attack"] for c in bucket),
                abl=statistics.mean(c["complexity"] for c in bucket),
                budget=statistics.mean(c["budget"] for c in bucket),
            ))
    lines.append("")

    lines.append("## Outliers to review")
    lines.append("")
    outliers = find_outliers(cards)
    if outliers:
        lines.append("| Severity | Card | Rarity | Cost | Level | HP | Attack | Abilities | Reason |")
        lines.append("|---|---|---|---:|---:|---:|---:|---|---|")
        for sev, card, reason in outliers[:40]:
            lines.append("| {sev} | {name} `{id}` | {rarity} | {cost} | {level} | {hp} | {atk} | {abilities} | {reason} |".format(
                sev=sev,
                name=card["name"],
                id=card["ID"],
                rarity=RARITY_LABEL.get(card["quality"], card["quality"]),
                cost=card["cost"],
                level=card["level"],
                hp=card["hp"],
                atk=card["attack"],
                abilities=", ".join(name for name, _ in card["powers"]),
                reason=reason,
            ))
    else:
        lines.append("No critical rate outliers found by the heuristic.")
    lines.append("")

    lines.append("## Strict power-creep candidates")
    lines.append("")
    dominated = find_strict_dominance(level1)
    if dominated:
        lines.append("These are same-cost level-1 monster pairs where a higher-rarity card is at least as good on HP, primary attack, and ability count, with one or more strictly higher. These need design review; some may be justified by ability drawbacks that the heuristic cannot understand.")
        lines.append("")
        lines.append("| Lower-rarity card | Higher-rarity card | Cost | Why flagged |")
        lines.append("|---|---|---:|---|")
        for low, high, why in dominated[:30]:
            lines.append(f"| {low['name']} `{low['ID']}` ({RARITY_LABEL.get(low['quality'], low['quality'])}) | {high['name']} `{high['ID']}` ({RARITY_LABEL.get(high['quality'], high['quality'])}) | {low['cost']} | {why} |")
    else:
        lines.append("No strict same-cost rarity upgrades found among level-1 collectible monsters.")
    lines.append("")

    lines.append("## Special/tutorial cards")
    lines.append("")
    lines.append("Cards with `flags=0` are intentionally excluded from random reward pools and the web prototype's generated decks. They can remain extreme because they teach mechanics or act as scripted bosses.")
    lines.append("")
    lines.append("| Card | Type | Rarity | Cost | HP | Attack | Abilities |")
    lines.append("|---|---|---|---:|---:|---:|---|")
    for card in special:
        lines.append("| {name} `{id}` | {type} | {rarity} | {cost} | {hp} | {atk} | {abilities} |".format(
            name=card["name"],
            id=card["ID"],
            type=card["type"],
            rarity=RARITY_LABEL.get(card["quality"], card["quality"]),
            cost=card["cost"],
            hp=card["hp"],
            atk=card["attack"],
            abilities=", ".join(name for name, _ in card["powers"]),
        ))
    lines.append("")

    lines.append("## Honest evaluation")
    lines.append("")
    lines.append("- The collectible level-1 monster set is not wildly pay-to-win on raw HP: Common/Rare averages sit close together at costs 1-4.")
    lines.append("- Legendary averages do jump at cost 3, so Legendary designs should be reviewed card-by-card and pushed toward conditional/choice-heavy effects instead of more HP plus more attack.")
    lines.append("- The worst apparent power-creep example is actually the `flags=0` tutorial card Vibranium Armor; Gerbip king has been moved out of the 1-cost slot and remains non-collectible. The bug was exposure: the web prototype treated special cards as normal random cards.")
    lines.append("- The production offline reward pool is already curated; keep it that way and do not switch rewards to sample from all cards without applying `flags=1` and budget checks.")
    lines.append("")
    lines.append("## Recommended next design pass")
    lines.append("")
    lines.append("1. For each Legendary that exceeds its same-cost Common/Rare budget, remove 1-2 HP or raise cost before adding any new abilities.")
    lines.append("2. Prefer legendary hooks like delayed bonuses, positional trade-offs, once-per-battle choices, or synergy enablers; avoid unconditional `better body + better attack` packages.")
    lines.append("3. Keep commons as efficient baseline bodies with one obvious job. They should be boring-good, not obsolete.")
    lines.append("4. Add this audit to CI once the final budget formula is agreed by design.")
    lines.append("")
    return "\n".join(lines)


def find_outliers(cards: list[dict]) -> list[tuple[str, dict, str]]:
    results: list[tuple[str, dict, str]] = []
    monsters = [c for c in cards if c["type"] == "monster"]
    collectible = [c for c in monsters if c["flags"] == 1]
    by_cost_level: dict[tuple[int, int], list[dict]] = defaultdict(list)
    for card in collectible:
        by_cost_level[(card["cost"], card["level"])].append(card)

    thresholds = {}
    for key, bucket in by_cost_level.items():
        if len(bucket) >= 4:
            budgets = [c["budget"] for c in bucket]
            thresholds[key] = percentile(budgets, 90) + 2.0

    for card in monsters:
        if card["flags"] == 0:
            if card["cost"] <= 1 and (card["hp"] >= 8 or card["attack"] >= 3 or card["complexity"] >= 3):
                results.append(("Info", card, "scripted/tutorial card; must stay out of random/prototype pools"))
            continue
        key = (card["cost"], card["level"])
        threshold = thresholds.get(key)
        if threshold and card["budget"] > threshold and card["quality"] == "epic":
            results.append(("Review", card, f"Legendary budget {card['budget']:.1f} above same cost/level threshold {threshold:.1f}"))
        if card["cost"] <= 1 and card["hp"] >= 7 and card["quality"] == "epic":
            results.append(("Critical", card, "1-cost Legendary with boss-level HP"))
    return sorted(results, key=lambda item: {"Critical": 0, "Review": 1, "Info": 2}.get(item[0], 9))


def find_strict_dominance(cards: list[dict]) -> list[tuple[dict, dict, str]]:
    results: list[tuple[dict, dict, str]] = []
    for low in cards:
        for high in cards:
            if low is high:
                continue
            if low["cost"] != high["cost"] or low["kind"] != high["kind"]:
                continue
            if RARITY_ORDER.get(high["quality"], 0) <= RARITY_ORDER.get(low["quality"], 0):
                continue
            if high["hp"] >= low["hp"] and high["attack"] >= low["attack"] and high["complexity"] >= low["complexity"]:
                diffs = []
                if high["hp"] > low["hp"]:
                    diffs.append(f"HP {low['hp']} -> {high['hp']}")
                if high["attack"] > low["attack"]:
                    diffs.append(f"attack {low['attack']} -> {high['attack']}")
                if high["complexity"] > low["complexity"]:
                    diffs.append(f"abilities {low['complexity']} -> {high['complexity']}")
                if diffs:
                    results.append((low, high, ", ".join(diffs)))
    # Keep the output readable and deterministic.
    results.sort(key=lambda x: (x[0]["cost"], RARITY_ORDER.get(x[0]["quality"], 0), RARITY_ORDER.get(x[1]["quality"], 0), x[0]["ID"], x[1]["ID"]))
    return results


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--markdown", action="store_true", help="Print a Markdown report")
    parser.add_argument("--fail-on-critical", action="store_true", help="Exit non-zero if collectible critical outliers are found")
    args = parser.parse_args()

    cards = read_cards()
    if args.markdown:
        print(summarize(cards))
    else:
        print(f"cards={len(cards)} collectible={sum(1 for c in cards if c['flags'] == 1)} special={sum(1 for c in cards if c['flags'] == 0)}")
        for sev, card, reason in find_outliers(cards):
            print(f"{sev}: {card['ID']} {card['name']} cost={card['cost']} hp={card['hp']} atk={card['attack']} - {reason}")

    if args.fail_on_critical:
        for sev, card, _ in find_outliers(cards):
            if sev == "Critical" and card["flags"] == 1:
                return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
