#!/usr/bin/env python3
"""Regenerate the native campaign module from the ONE canonical source.

`content/campaign_data.json` is the canonical campaign definition (regions,
nodes, tokens, starter collection). This script turns that single file into
`src/manager/campaign_data_generated.lua` — the copy the Android/Lua engine
loads through `src/manager/campaign_data.lua`.

The web shell that used to carry the campaign as an HTML app has been
removed; this generator is the Android side of the "one canonical campaign"
rule: edit the JSON, re-run this script, and the native campaign stays in
sync. There must be no hand-maintained copy of the level list anywhere else.

Usage:
    python3 scripts/refresh_campaign_data.py               # regenerate Lua
    python3 scripts/refresh_campaign_data.py --verify      # assert the Lua matches the JSON
    python3 scripts/refresh_campaign_data.py --emit-lua /path/out.lua
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANON = ROOT / "content" / "campaign_data.json"
LUA_OUT = ROOT / "src" / "manager" / "campaign_data_generated.lua"


def load_canon() -> dict:
    return json.loads(CANON.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Lua emission
# ---------------------------------------------------------------------------

def lua_str(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\{ord(ch):03d}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def lua_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        return "{ " + ", ".join(lua_value(x) for x in v) + " }"
    if isinstance(v, dict):
        parts = []
        for k, val in v.items():
            key = k if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k) else f"[{lua_str(k)}]"
            parts.append(f"{key} = {lua_value(val)}")
        return "{ " + ", ".join(parts) + " }"
    raise TypeError(f"cannot serialize {type(v)} to Lua: {v!r}")


def node_to_lua(node: dict) -> dict:
    out = {k: node[k] for k in ("id", "type", "name", "icon", "hp", "exp", "desc")
           if k in node}
    if "enemyName" in node:
        out["enemy_name"] = node["enemyName"]
    if "deckIds" in node:
        out["deck_ids"] = node["deckIds"]
    if "pool" in node:
        p = node["pool"]
        out["pool"] = {
            "kinds": p["kinds"],
            "lv_min": p["lvMin"],
            "lv_max": p["lvMax"],
            "size": p["size"],
        }
    if "power" in node:
        out["power"] = node["power"]
    if node.get("bossTitle") or node.get("type") == "boss":
        out["boss"] = True
    if node.get("final"):
        out["final"] = True
    return out


def token_to_lua(key: str, tok: dict) -> str:
    # The engine expresses attack as a melee power; synthesize it from
    # the JSON's flat `attack` number.
    out = {
        "uid": tok["id"],
        "name": tok["name"],
        "kind": tok["kind"],
        "cost": tok["cost"],
        "hp": tok["hp"],
        "type": "monster",
        "quality": "normal",
        "level": 1,
        "res_path": "",
        "power_list": [{"name": "melee", "value": tok["attack"], "target_type": "enemy", "type": "passive"}],
    }
    return f"{key} = {lua_value(out)}"


def emit_lua(data: dict) -> str:
    lines = [
        "-- campaign_data_generated.lua",
        "-- GENERATED by scripts/refresh_campaign_data.py from",
        "-- content/campaign_data.json. DO NOT EDIT BY HAND — edit the JSON and",
        "-- re-run the generator.",
        "--",
        "-- The native campaign module (src/manager/campaign_data.lua) can require",
        "-- this file and read M.REGIONS / M.TOKENS / M.STARTER_COLLECTION instead",
        "-- of hand-maintaining its own copies.",
        "local M = {}",
        "",
        "M.STARTER_COLLECTION = " + lua_value(data["starterCollection"]),
        "",
        "M.TOKENS = {",
    ]
    for key, tok in data["tokens"].items():
        lines.append("    " + token_to_lua(key, tok) + ",")
    lines.append("}")
    lines.append("")
    lines.append("M.REGIONS = {")
    for region in data["regions"]:
        lines.append("    " + lua_value({
            "id": region["id"], "name": region["name"], "sub": region["sub"],
            "faction": region["faction"], "icon": region["icon"],
            "nodes": [node_to_lua(n) for n in region["nodes"]],
        }) + ",")
    lines.append("}")
    lines.append("")
    lines.append("return M")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--emit-lua", type=Path, default=LUA_OUT)
    args = parser.parse_args()

    data = load_canon()

    if args.verify:
        ok = True
        if args.emit_lua.exists():
            # coarse check that the generated Lua contains every node id
            text = args.emit_lua.read_text(encoding="utf-8")
            ids = [n["id"] for r in data["regions"] for n in r["nodes"]]
            missing = [i for i in ids if f'id = "{i}"' not in text]
            if missing:
                print(f"ERROR: {args.emit_lua} missing nodes {missing}", file=sys.stderr)
                ok = False
            else:
                print(f"OK: {args.emit_lua}")
        # round-trip check: emitting from the JSON must reproduce the file
        emitted = emit_lua(data)
        if args.emit_lua.exists() and args.emit_lua.read_text(encoding="utf-8") != emitted:
            print(f"ERROR: {args.emit_lua} is stale (re-run the generator)", file=sys.stderr)
            ok = False
        return 0 if ok else 1

    # ---- regenerate ----
    args.emit_lua.write_text(emit_lua(data), encoding="utf-8")
    print(f"Wrote {args.emit_lua.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
