#!/usr/bin/env python3
"""Regenerate every platform's copy of the Shadow Road campaign from ONE source.

`content/campaign_data.json` is the canonical campaign definition (regions,
nodes, tokens, starter collection). This script turns that single file into:

  * the embedded `const CAMPAIGN_DATA = {...};` blob inside `index.html` and
    `build/web/game.html` (the web shell), and
  * `src/manager/campaign_data_generated.lua` (the Android/Lua shell), and
  * a plain mirror at `build/web/campaign_data.json`.

This implements the "one canonical campaign" rule from the consolidation plan:
edit the JSON, re-run this script, and every platform stays in sync. There must
be no hand-maintained copy of the level list anywhere else.

Usage:
    python3 scripts/refresh_campaign_data.py               # regenerate everything
    python3 scripts/refresh_campaign_data.py --verify      # assert all copies match the JSON
    python3 scripts/refresh_campaign_data.py --emit-lua /path/out.lua
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANON = ROOT / "content" / "campaign_data.json"
WEB_JSON = ROOT / "build" / "web" / "campaign_data.json"
HTML_TARGETS = [ROOT / "index.html", ROOT / "build" / "web" / "game.html"]
LUA_OUT = ROOT / "src" / "manager" / "campaign_data_generated.lua"

# In the HTML the blob is one compact line; re-running replaces just that line.
BLOB_RE = re.compile(r"const CAMPAIGN_DATA = .*?;\n", re.DOTALL)
# First-time wiring: replace the old inline literals (STARTER_COLLECTION, TOKENS,
# REGIONS) that used to sit between these anchors.
INSERT_START = "const STARTER_COLLECTION = [\n"
INSERT_END = "\nconst ALL_NODES = "
INSERT_RE = re.compile(
    r"const STARTER_COLLECTION = \[[\s\S]*?\nconst ALL_NODES = ", re.DOTALL
)


def load_canon() -> dict:
    return json.loads(CANON.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Lua emission
# ---------------------------------------------------------------------------

def lua_str(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\{ord(ch):03d}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def lua_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        return "{ " + ", ".join(lua_value(x) for x in v) + " }"
    if isinstance(v, dict):
        parts = []
        for k, val in v.items():
            key = k if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k) else f"[{lua_str(k)}]"
            parts.append(f"{key} = {lua_value(val)}")
        return "{ " + ", ".join(parts) + " }"
    raise TypeError(f"cannot serialize {type(v)} to Lua: {v!r}")


def node_to_lua(node: dict) -> dict:
    out = {k: node[k] for k in ("id", "type", "name", "icon", "hp", "exp", "desc")
           if k in node}
    if "enemyName" in node:
        out["enemy_name"] = node["enemyName"]
    if "deckIds" in node:
        out["deck_ids"] = node["deckIds"]
    if "pool" in node:
        p = node["pool"]
        out["pool"] = {
            "kinds": p["kinds"],
            "lv_min": p["lvMin"],
            "lv_max": p["lvMax"],
            "size": p["size"],
        }
    if "power" in node:
        out["power"] = node["power"]
    if node.get("bossTitle") or node.get("type") == "boss":
        out["boss"] = True
    if node.get("final"):
        out["final"] = True
    return out


def token_to_lua(key: str, tok: dict) -> str:
    # The web model stores attack as a flat number; the Lua engine expresses
    # attack as a melee power. Synthesize the melee power from `attack`.
    out = {
        "uid": tok["id"],
        "name": tok["name"],
        "kind": tok["kind"],
        "cost": tok["cost"],
        "hp": tok["hp"],
        "type": "monster",
        "quality": "normal",
        "level": 1,
        "res_path": "",
        "power_list": [{"name": "melee", "value": tok["attack"], "target_type": "enemy", "type": "passive"}],
    }
    return f"{key} = {lua_value(out)}"


def emit_lua(data: dict) -> str:
    lines = [
        "-- campaign_data_generated.lua",
        "-- GENERATED by scripts/refresh_campaign_data.py from",
        "-- content/campaign_data.json. DO NOT EDIT BY HAND — edit the JSON and",
        "-- re-run the generator.",
        "--",
        "-- The native campaign module (src/manager/campaign_data.lua) can require",
        "-- this file and read M.REGIONS / M.TOKENS / M.STARTER_COLLECTION instead",
        "-- of hand-maintaining its own copies.",
        "local M = {}",
        "",
        "M.STARTER_COLLECTION = " + lua_value(data["starterCollection"]),
        "",
        "M.TOKENS = {",
    ]
    for key, tok in data["tokens"].items():
        lines.append("    " + token_to_lua(key, tok) + ",")
    lines.append("}")
    lines.append("")
    lines.append("M.REGIONS = {")
    for region in data["regions"]:
        lines.append("    " + lua_value({
            "id": region["id"], "name": region["name"], "sub": region["sub"],
            "faction": region["faction"], "icon": region["icon"],
            "nodes": [node_to_lua(n) for n in region["nodes"]],
        }) + ",")
    lines.append("}")
    lines.append("")
    lines.append("return M")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML embedding
# ---------------------------------------------------------------------------

def embed_blob(html: str, blob: str) -> str:
    if "const CAMPAIGN_DATA = " in html:
        new_html, n = BLOB_RE.subn(f"const CAMPAIGN_DATA = {blob};\n", html, count=1)
        if n != 1:
            raise RuntimeError("found CAMPAIGN_DATA marker but could not replace it")
        return new_html

    # First-time wiring: swap the old inline literals for the blob + derivations.
    replacement = (
        "const CAMPAIGN_DATA = " + blob + ";\n"
        "\n"
        "// Canonical campaign content (content/campaign_data.json). Regenerated by\n"
        "// scripts/refresh_campaign_data.py — edit the JSON, not this block.\n"
        "const REGIONS = CAMPAIGN_DATA.regions;\n"
        "const TOKENS = CAMPAIGN_DATA.tokens;\n"
        "const STARTER_COLLECTION = CAMPAIGN_DATA.starterCollection;\n"
        "\n"
        "const ALL_NODES = "
    )
    new_html, n = INSERT_RE.subn(lambda _m: replacement, html, count=1)
    if n != 1:
        raise RuntimeError("could not locate the inline campaign literals to replace")
    return new_html


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def extract_embedded(html: str) -> dict:
    m = re.search(r"const CAMPAIGN_DATA = (\{.*?\});\n", html, re.DOTALL)
    if not m:
        raise RuntimeError("no CAMPAIGN_DATA blob found in HTML")
    return json.loads(m.group(1))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--emit-lua", type=Path, default=LUA_OUT)
    args = parser.parse_args()

    data = load_canon()
    blob = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

    if args.verify:
        ok = True
        for target in HTML_TARGETS:
            try:
                embedded = extract_embedded(target.read_text(encoding="utf-8"))
                if embedded != data:
                    print(f"MISMATCH: {target} differs from {CANON.name}", file=sys.stderr)
                    ok = False
                else:
                    print(f"OK: {target}")
            except RuntimeError as e:
                print(f"ERROR: {target}: {e}", file=sys.stderr)
                ok = False
        if args.emit_lua.exists():
            # coarse check that the generated Lua contains every node id
            text = args.emit_lua.read_text(encoding="utf-8")
            ids = [n["id"] for r in data["regions"] for n in r["nodes"]]
            missing = [i for i in ids if f'id = "{i}"' not in text]
            if missing:
                print(f"ERROR: {args.emit_lua} missing nodes {missing}", file=sys.stderr)
                ok = False
            else:
                print(f"OK: {args.emit_lua}")
        return 0 if ok else 1

    # ---- regenerate ----
    WEB_JSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {WEB_JSON.relative_to(ROOT)}")

    for target in HTML_TARGETS:
        html = target.read_text(encoding="utf-8")
        target.write_text(embed_blob(html, blob), encoding="utf-8")
        print(f"Wrote {target.relative_to(ROOT)}")

    args.emit_lua.write_text(emit_lua(data), encoding="utf-8")
    print(f"Wrote {args.emit_lua.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
